version: 2.1

jobs:
  hello-world:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Say Hello
          command: echo "Hello, World!"
      - run:
          name: Say Hi Team
          command: echo "Hi, Team!"

workflows:
  version: 2
  hello:
    jobs:
      - hello-world
