version: 2.1

jobs:
  hello-world:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Say Hello
          command: echo "Hello, World!"
      - run:
          name: Say Hi Team
          command: echo "Hi, Team!"

  trivy-scan:
    docker:
      - image: aquasec/trivy:latest
    steps:
      - checkout
      - run:
          name: Run Trivy Scan
          command: trivy filesystem --exit-code 1 --no-progress .

workflows:
  version: 2
  hello_and_scan:
    jobs:
      - hello-world
      - trivy-scan
